### ISSUE TITLE
Error when following someone and trying to grade posts

### ISSUE THREAD

**Issue by RokKuzner** [RokKuzner/FriendFace#3]
When a user follows someone and enters the main page the 500 error page is showed. When looking into the log, this is the error:
```
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Rok\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rok\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rok\Documents\Programiranje\FriendFace\decorators.py", line 15, in decorated_function
    return f(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rok\Documents\Programiranje\FriendFace\app\views.py", line 20, in home
    posts = alg.get_personalized_posts(request.session['current_user'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rok\Documents\Programiranje\FriendFace\algorythms.py", line 24, in get_personalized_posts
    users_following_posts += db.get_posts_by_user(user)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_posts_by_user() missing 1 required positional argument: 'current_user'
```

Deadline: 15. 1. 2024, 18:30

**Comment by RokKuzner** [comment]
Error resolved!

**Comment by RokKuzner** [comment]
Error resolved!
